"""empty message

Revision ID: 309a3b8c2533
Revises: 6e0fed3ef0ee
Create Date: 2020-04-03 17:05:08.480671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a3b8c2533'
down_revision = '6e0fed3ef0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previous_record', 'ca',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('previous_record', 'thal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('previous_record', 'thal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('previous_record', 'ca',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
