"""empty message

Revision ID: c8446c6edbee
Revises: 309a3b8c2533
Create Date: 2020-04-05 14:47:30.156360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8446c6edbee'
down_revision = '309a3b8c2533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previousrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('trestbps', sa.Integer(), nullable=True),
    sa.Column('chol', sa.Integer(), nullable=True),
    sa.Column('fbs', sa.Integer(), nullable=True),
    sa.Column('restecg', sa.Integer(), nullable=True),
    sa.Column('thalach', sa.Integer(), nullable=True),
    sa.Column('exang', sa.Integer(), nullable=True),
    sa.Column('oldpeak', sa.Float(), nullable=True),
    sa.Column('slope', sa.Integer(), nullable=True),
    sa.Column('ca', sa.Float(), nullable=True),
    sa.Column('thal', sa.Float(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('previous_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previous_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trestbps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fbs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('restecg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thalach', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exang', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('oldpeak', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slope', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ca', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('thal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='previous_record_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='previous_record_pkey')
    )
    op.drop_table('previousrecord')
    # ### end Alembic commands ###
